# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equipment.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Equipment(object):
    def setupUi(self, Equipment):
        Equipment.setObjectName("Equipment")
        Equipment.resize(691, 595)
        self.verticalLayout = QtWidgets.QVBoxLayout(Equipment)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pb_exit = QtWidgets.QPushButton(Equipment)
        self.pb_exit.setObjectName("pb_exit")
        self.horizontalLayout_2.addWidget(self.pb_exit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.list_wear = QtWidgets.QListWidget(Equipment)
        self.list_wear.setObjectName("list_wear")
        self.horizontalLayout.addWidget(self.list_wear)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pb_wear = QtWidgets.QPushButton(Equipment)
        self.pb_wear.setObjectName("pb_wear")
        self.verticalLayout_2.addWidget(self.pb_wear)
        self.pb_unworn = QtWidgets.QPushButton(Equipment)
        self.pb_unworn.setObjectName("pb_unworn")
        self.verticalLayout_2.addWidget(self.pb_unworn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.list_unworn = QtWidgets.QListWidget(Equipment)
        self.list_unworn.setObjectName("list_unworn")
        self.horizontalLayout.addWidget(self.list_unworn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Equipment)
        self.pb_exit.clicked.connect(Equipment.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Equipment)

    def retranslateUi(self, Equipment):
        _translate = QtCore.QCoreApplication.translate
        Equipment.setWindowTitle(_translate("Equipment", "Dialog"))
        self.pb_exit.setText(_translate("Equipment", "나가기"))
        self.pb_wear.setText(_translate("Equipment", "착용"))
        self.pb_unworn.setText(_translate("Equipment", "해제"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Equipment = QtWidgets.QDialog()
    ui = Ui_Equipment()
    ui.setupUi(Equipment)
    Equipment.show()
    sys.exit(app.exec_())
