# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gard_name.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(327, 372)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(30, 30, 30, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_gard_type = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_gard_type.sizePolicy().hasHeightForWidth())
        self.lb_gard_type.setSizePolicy(sizePolicy)
        self.lb_gard_type.setMinimumSize(QtCore.QSize(250, 0))
        self.lb_gard_type.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_gard_type.setFont(font)
        self.lb_gard_type.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_gard_type.setObjectName("lb_gard_type")
        self.verticalLayout.addWidget(self.lb_gard_type)
        self.lb_gard_img = QtWidgets.QLabel(Dialog)
        self.lb_gard_img.setText("")
        self.lb_gard_img.setObjectName("lb_gard_img")
        self.verticalLayout.addWidget(self.lb_gard_img)
        self.le_gard_name = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_gard_name.setFont(font)
        self.le_gard_name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.le_gard_name.setObjectName("le_gard_name")
        self.verticalLayout.addWidget(self.le_gard_name)
        self.pb_save = QtWidgets.QPushButton(Dialog)
        self.pb_save.setObjectName("pb_save")
        self.verticalLayout.addWidget(self.pb_save)

        self.retranslateUi(Dialog)
        self.pb_save.clicked.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lb_gard_type.setText(_translate("Dialog", "수호대명"))
        self.pb_save.setText(_translate("Dialog", "저장"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
