# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gard_name.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(327, 426)
        self.lb_gard_type = QtWidgets.QLabel(Dialog)
        self.lb_gard_type.setGeometry(QtCore.QRect(37, 31, 250, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_gard_type.sizePolicy().hasHeightForWidth())
        self.lb_gard_type.setSizePolicy(sizePolicy)
        self.lb_gard_type.setMinimumSize(QtCore.QSize(250, 0))
        self.lb_gard_type.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.lb_gard_type.setFont(font)
        self.lb_gard_type.setStyleSheet("color: rgb(255, 255, 255);font-weight: bold;")
        self.lb_gard_type.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_gard_type.setObjectName("lb_gard_type")
        self.le_gard_name = QtWidgets.QLineEdit(Dialog)
        self.le_gard_name.setGeometry(QtCore.QRect(85, 346, 150, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_gard_name.setFont(font)
        self.le_gard_name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.le_gard_name.setObjectName("le_gard_name")
        self.pb_save = QtWidgets.QPushButton(Dialog)
        self.pb_save.setGeometry(QtCore.QRect(115, 379, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pb_save.setFont(font)
        self.pb_save.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 190, 11, 255), stop:1 rgba(251, 86, 7, 255));\n"
"    border-radius: 20px;\n"
"}")
        self.pb_save.setObjectName("pb_save")
        self.lb_gard_frame = QtWidgets.QLabel(Dialog)
        self.lb_gard_frame.setGeometry(QtCore.QRect(22, 10, 279, 72))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_gard_frame.sizePolicy().hasHeightForWidth())
        self.lb_gard_frame.setSizePolicy(sizePolicy)
        self.lb_gard_frame.setMinimumSize(QtCore.QSize(250, 0))
        self.lb_gard_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lb_gard_frame.setFont(font)
        self.lb_gard_frame.setText("")
        self.lb_gard_frame.setPixmap(QtGui.QPixmap("../img_src/name/light_name.png"))
        self.lb_gard_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_gard_frame.setObjectName("lb_gard_frame")
        self.lb_gard_img = QtWidgets.QLabel(Dialog)
        self.lb_gard_img.setGeometry(QtCore.QRect(27, 100, 270, 220))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_gard_img.sizePolicy().hasHeightForWidth())
        self.lb_gard_img.setSizePolicy(sizePolicy)
        self.lb_gard_img.setMinimumSize(QtCore.QSize(270, 220))
        self.lb_gard_img.setMaximumSize(QtCore.QSize(270, 220))
        self.lb_gard_img.setText("")
        self.lb_gard_img.setObjectName("lb_gard_img")
        self.lb_gard_frame.raise_()
        self.lb_gard_type.raise_()
        self.le_gard_name.raise_()
        self.pb_save.raise_()
        self.lb_gard_img.raise_()

        self.retranslateUi(Dialog)
        self.pb_save.clicked.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lb_gard_type.setText(_translate("Dialog", "수호대명"))
        self.pb_save.setText(_translate("Dialog", "저장"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
